//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageUploader.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainPage___Copy__3_ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPage___Copy__3_() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageUploader.UI.Resources.Strings.MainPage - Copy (3)", typeof(MainPage___Copy__3_).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Game Package Manager.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced: List available tenants.
        /// </summary>
        public static string ChooseTenantButtonText {
            get {
                return ResourceManager.GetString("ChooseTenantButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game packages speed up uploads, ensure secure installs, and optimize Xbox performance. Just add build files and a config file .
        /// </summary>
        public static string MakeAPackageBodyTextOne {
            get {
                return ResourceManager.GetString("MakeAPackageBodyTextOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , then upload..
        /// </summary>
        public static string MakeAPackageBodyTextTwo {
            get {
                return ResourceManager.GetString("MakeAPackageBodyTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Learn more).
        /// </summary>
        public static string MakeAPackageBodyURLText {
            get {
                return ResourceManager.GetString("MakeAPackageBodyURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create package.
        /// </summary>
        public static string MakeAPackageButtonText {
            get {
                return ResourceManager.GetString("MakeAPackageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a package.
        /// </summary>
        public static string MakeAPackageTextBlockTitle {
            get {
                return ResourceManager.GetString("MakeAPackageTextBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakePkg.exe was not found. Please install the GDK in order to package game contents..
        /// </summary>
        public static string MakePackageNotFoundErrorMsg {
            get {
                return ResourceManager.GetString("MakePackageNotFoundErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInButtonContent {
            get {
                return ResourceManager.GetString("SignInButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are attempting to retrieve your sign-in information. If a browser page does not open within a few seconds, please click the sign-in button again to retry..
        /// </summary>
        public static string SignInLogginInText {
            get {
                return ResourceManager.GetString("SignInLogginInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For seamless access to your Product ID and publishing destinations, sign in to your Microsoft Partner Center account. This step is optional if you&apos;re only creating game packages without configurations, but it&apos;s required for anyone planning to upload packages, retrieve Product Ids, or link them to configuration files..
        /// </summary>
        public static string SignInPreLoginText {
            get {
                return ResourceManager.GetString("SignInPreLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInTextBlockTitle {
            get {
                return ResourceManager.GetString("SignInTextBlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Package Creation Tool bundles your game files, assets, and metadata into a structured package, ensuring consistency and compliance for a faster, more reliable upload..
        /// </summary>
        public static string SubTitleTextBlock {
            get {
                return ResourceManager.GetString("SubTitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a package and upload it to Microsoft Partner Center.
        /// </summary>
        public static string TitleTextBlock {
            get {
                return ResourceManager.GetString("TitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your game package to Partner Center to distribute and manage it on Xbox. Get started with a completed package and a Microsoft account..
        /// </summary>
        public static string UploadPackageBlockBody {
            get {
                return ResourceManager.GetString("UploadPackageBlockBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload package.
        /// </summary>
        public static string UploadPackageBlockButtonText {
            get {
                return ResourceManager.GetString("UploadPackageBlockButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a package (sign in required).
        /// </summary>
        public static string UploadPackageBlockTitle {
            get {
                return ResourceManager.GetString("UploadPackageBlockTitle", resourceCulture);
            }
        }
    }
}
