//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageUploader.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msixvc2Upload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msixvc2Upload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageUploader.UI.Resources.Strings.Msixvc2Upload", typeof(Msixvc2Upload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details.
        /// </summary>
        public static string AdditionalDetailsTitle {
            get {
                return ResourceManager.GetString("AdditionalDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the content directory..
        /// </summary>
        public static string BrowseContentPathHelpText {
            get {
                return ResourceManager.GetString("BrowseContentPathHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your loose file directory containing a MicrosoftGame.config. Add a layout file under Additional Details..
        /// </summary>
        public static string BuildLocationText {
            get {
                return ResourceManager.GetString("BuildLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build location.
        /// </summary>
        public static string BuildLocationTitle {
            get {
                return ResourceManager.GetString("BuildLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and return to the home page..
        /// </summary>
        public static string CancelButtonHelpText {
            get {
                return ResourceManager.GetString("CancelButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelContentText {
            get {
                return ResourceManager.GetString("CancelContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the content map location.
        /// </summary>
        public static string ContentMapPathBoxDefaultText {
            get {
                return ResourceManager.GetString("ContentMapPathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the content directory.
        /// </summary>
        public static string ContentPathBoxDefaultText {
            get {
                return ResourceManager.GetString("ContentPathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content path.
        /// </summary>
        public static string ContentPathTitleText {
            get {
                return ResourceManager.GetString("ContentPathTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination and market for the package upload..
        /// </summary>
        public static string DestinationSubtitleText {
            get {
                return ResourceManager.GetString("DestinationSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationTitleText {
            get {
                return ResourceManager.GetString("DestinationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string FamilyTitleText {
            get {
                return ResourceManager.GetString("FamilyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder size.
        /// </summary>
        public static string FolderSizeTitleText {
            get {
                return ResourceManager.GetString("FolderSizeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file/content map.
        /// </summary>
        public static string LayoutFileMapTitle {
            get {
                return ResourceManager.GetString("LayoutFileMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string MarketTitleText {
            get {
                return ResourceManager.GetString("MarketTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string OptionalText {
            get {
                return ResourceManager.GetString("OptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Identity name.
        /// </summary>
        public static string PackageIdentityNameTitleText {
            get {
                return ResourceManager.GetString("PackageIdentityNameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductNameText {
            get {
                return ResourceManager.GetString("ProductNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store ID.
        /// </summary>
        public static string StoreIdTitleText {
            get {
                return ResourceManager.GetString("StoreIdTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point to your loose file directory for your PC game containing a MicrosoftGame.config and we will package and upload using the MSIXVC2 format..
        /// </summary>
        public static string SubtitleText {
            get {
                return ResourceManager.GetString("SubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Loose Files (PC only).
        /// </summary>
        public static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Package.
        /// </summary>
        public static string UploadButtonContentText {
            get {
                return ResourceManager.GetString("UploadButtonContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start packaging and uploading the loose files..
        /// </summary>
        public static string UploadButtonHelpText {
            get {
                return ResourceManager.GetString("UploadButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Preview.
        /// </summary>
        public static string UploadPreviewTitleText {
            get {
                return ResourceManager.GetString("UploadPreviewTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the folder path for SubmissionValidator.dll.
        /// </summary>
        public static string ValidatorPathBoxDefaultText {
            get {
                return ResourceManager.GetString("ValidatorPathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path for SubmissionValidator.dll.
        /// </summary>
        public static string ValidatorPathTitleText {
            get {
                return ResourceManager.GetString("ValidatorPathTitleText", resourceCulture);
            }
        }
    }
}
