//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageUploader.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackagingProgress {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackagingProgress() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageUploader.UI.Resources.Strings.PackagingProgress", typeof(PackagingProgress).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel packaging.
        /// </summary>
        public static string CancelPackagingButtonContentText {
            get {
                return ResourceManager.GetString("CancelPackagingButtonContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying and encrypting data....
        /// </summary>
        public static string CopyingAndEncryptingText {
            get {
                return ResourceManager.GetString("CopyingAndEncryptingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your package ready....
        /// </summary>
        public static string PackagingProgressTitleText {
            get {
                return ResourceManager.GetString("PackagingProgressTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging....
        /// </summary>
        public static string PackingText {
            get {
                return ResourceManager.GetString("PackingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % complete.
        /// </summary>
        public static string PercentComplete {
            get {
                return ResourceManager.GetString("PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating files....
        /// </summary>
        public static string ValidatingFilesText {
            get {
                return ResourceManager.GetString("ValidatingFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying package contents....
        /// </summary>
        public static string VerifyingPackageContentsText {
            get {
                return ResourceManager.GetString("VerifyingPackageContentsText", resourceCulture);
            }
        }
    }
}
