//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageUploader.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackageUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageUploader.UI.Resources.Strings.PackageUpload", typeof(PackageUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details.
        /// </summary>
        public static string AditionalDetailsText {
            get {
                return ResourceManager.GetString("AditionalDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch {0} wasn&apos;t found..
        /// </summary>
        public static string BranchNotFoundErrMsg {
            get {
                return ResourceManager.GetString("BranchNotFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the package file..
        /// </summary>
        public static string BrowsePackagePathHelpText {
            get {
                return ResourceManager.GetString("BrowsePackagePathHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a BuildId mismatch in the Submission Validator log file..
        /// </summary>
        public static string BuildIdMismatchSubValErrMsg {
            get {
                return ResourceManager.GetString("BuildIdMismatchSubValErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the operation..
        /// </summary>
        public static string CancelButtonHelpText {
            get {
                return ResourceManager.GetString("CancelButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelContentText {
            get {
                return ResourceManager.GetString("CancelContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the location of the package.
        /// </summary>
        public static string ConfirmLocationSubtitleText {
            get {
                return ResourceManager.GetString("ConfirmLocationSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string DestinationTitleText {
            get {
                return ResourceManager.GetString("DestinationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory wasn&apos;t found..
        /// </summary>
        public static string DirectoryNotFoundErrMsg {
            get {
                return ResourceManager.GetString("DirectoryNotFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while extracting the package information..
        /// </summary>
        public static string ErrorExtractingInfoErrMsg {
            get {
                return ResourceManager.GetString("ErrorExtractingInfoErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the market groups..
        /// </summary>
        public static string ErrorGettingMarketGroupsErrMsg {
            get {
                return ResourceManager.GetString("ErrorGettingMarketGroupsErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while getting the product information..
        /// </summary>
        public static string ErrorGettingProdInfo {
            get {
                return ResourceManager.GetString("ErrorGettingProdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing the package..
        /// </summary>
        public static string ErrorProcessingPackageErrMsg {
            get {
                return ResourceManager.GetString("ErrorProcessingPackageErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while selecting the file..
        /// </summary>
        public static string ErrorSelectingFileErrMsg {
            get {
                return ResourceManager.GetString("ErrorSelectingFileErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading the package..
        /// </summary>
        public static string ErrUploadPackageErrMsg {
            get {
                return ResourceManager.GetString("ErrUploadPackageErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string ExpectedText {
            get {
                return ResourceManager.GetString("ExpectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string FamilyTitleText {
            get {
                return ResourceManager.GetString("FamilyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FileNameTitleText {
            get {
                return ResourceManager.GetString("FileNameTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string FoundText {
            get {
                return ResourceManager.GetString("FoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is invalid..
        /// </summary>
        public static string InvalidFilePathErrMsg {
            get {
                return ResourceManager.GetString("InvalidFilePathErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string MarketTitleText {
            get {
                return ResourceManager.GetString("MarketTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No branches were found for this product..
        /// </summary>
        public static string NoBranchesFoundErrMsg {
            get {
                return ResourceManager.GetString("NoBranchesFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product information.
        /// </summary>
        public static string NoProdInfoTitleText {
            get {
                return ResourceManager.GetString("NoProdInfoTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null branch/flight.
        /// </summary>
        public static string NullBranchFlightErrTitleText {
            get {
                return ResourceManager.GetString("NullBranchFlightErrTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package has no StoreId. Configure your StoreId in the MicrosoftGame.config file before building your package or manually enter it in Additional details..
        /// </summary>
        public static string PackageHasNoBigIdConfigureMsftGameCfgErrMsg {
            get {
                return ResourceManager.GetString("PackageHasNoBigIdConfigureMsftGameCfgErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package location.
        /// </summary>
        public static string PackageLocationTitleText {
            get {
                return ResourceManager.GetString("PackageLocationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the package file..
        /// </summary>
        public static string PackagePathHelpText {
            get {
                return ResourceManager.GetString("PackagePathHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package path.
        /// </summary>
        public static string PackagePathText {
            get {
                return ResourceManager.GetString("PackagePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product information isn&apos;t available. Please enter a valid StoreId and try again..
        /// </summary>
        public static string ProductInfoNotAvailableErrMsg {
            get {
                return ResourceManager.GetString("ProductInfoNotAvailableErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductNameText {
            get {
                return ResourceManager.GetString("ProductNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product with StoreId {0} wasn&apos;t found. Configure your product at https://aka.ms/mpc-ag..
        /// </summary>
        public static string ProductWithStoreIdNotFoundConfigHereErrMsg {
            get {
                return ResourceManager.GetString("ProductWithStoreIdNotFoundConfigHereErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a destination and market for the package upload.
        /// </summary>
        public static string SelectDestinationText {
            get {
                return ResourceManager.GetString("SelectDestinationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the package path.
        /// </summary>
        public static string SelectEnterPackagePathText {
            get {
                return ResourceManager.GetString("SelectEnterPackagePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a package file.
        /// </summary>
        public static string SelectPackageFileText {
            get {
                return ResourceManager.GetString("SelectPackageFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeTitleText {
            get {
                return ResourceManager.GetString("SizeTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreId.
        /// </summary>
        public static string StoreIdTitleText {
            get {
                return ResourceManager.GetString("StoreIdTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Submission Validator log wasn&apos;t found..
        /// </summary>
        public static string SubValLogNotFoundErrMsg {
            get {
                return ResourceManager.GetString("SubValLogNotFoundErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload package.
        /// </summary>
        public static string UploadButtonContentText {
            get {
                return ResourceManager.GetString("UploadButtonContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start uploading a package..
        /// </summary>
        public static string UploadButtonHelpText {
            get {
                return ResourceManager.GetString("UploadButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload was canceled..
        /// </summary>
        public static string UploadCancelledErrMsg {
            get {
                return ResourceManager.GetString("UploadCancelledErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate the package for uploading. The Xbox Game Package Manager retains these paths for easier access in the future..
        /// </summary>
        public static string UploadPackageSubtitleText {
            get {
                return ResourceManager.GetString("UploadPackageSubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a package.
        /// </summary>
        public static string UploadPackageTitleText {
            get {
                return ResourceManager.GetString("UploadPackageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string UploadPreviewTitleText {
            get {
                return ResourceManager.GetString("UploadPreviewTitleText", resourceCulture);
            }
        }
    }
}
