//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageUploader.UI.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackageCreation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageCreation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageUploader.UI.Resources.Strings.PackageCreation", typeof(PackageCreation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional details.
        /// </summary>
        public static string AdditionalDetailsTitle {
            get {
                return ResourceManager.GetString("AdditionalDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BrowseText {
            get {
                return ResourceManager.GetString("BrowseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your game files to package. Add a layout file under Additional Details. See docs for more information..
        /// </summary>
        public static string BuildLocationText {
            get {
                return ResourceManager.GetString("BuildLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build location.
        /// </summary>
        public static string BuildLocationTitle {
            get {
                return ResourceManager.GetString("BuildLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the content map location.
        /// </summary>
        public static string ContentMapPathBoxDefaultText {
            get {
                return ResourceManager.GetString("ContentMapPathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create package.
        /// </summary>
        public static string CreatePackageButtonText {
            get {
                return ResourceManager.GetString("CreatePackageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the Identity Data folder here or click to browse.
        /// </summary>
        public static string DragAndDropMessage {
            get {
                return ResourceManager.GetString("DragAndDropMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating package..
        /// </summary>
        public static string ErrorCreatingPackageErrorMsg {
            get {
                return ResourceManager.GetString("ErrorCreatingPackageErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create output directory.
        /// </summary>
        public static string FailedToCreateOutputDirectoryErrorMsg {
            get {
                return ResourceManager.GetString("FailedToCreateOutputDirectoryErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate a layout file.
        /// </summary>
        public static string FailedToGenerateLayoutFileErrorMsg {
            get {
                return ResourceManager.GetString("FailedToGenerateLayoutFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided folder does not contain a MicrosoftGame.config file.
        /// </summary>
        public static string FolderDoesNotContainConfigErrMsg {
            get {
                return ResourceManager.GetString("FolderDoesNotContainConfigErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the game&apos;s location.
        /// </summary>
        public static string GamePathBoxDefaultText {
            get {
                return ResourceManager.GetString("GamePathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path.
        /// </summary>
        public static string GamePathTitleText {
            get {
                return ResourceManager.GetString("GamePathTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating layout file..
        /// </summary>
        public static string GeneratingLayoutFileErrorMsg {
            get {
                return ResourceManager.GetString("GeneratingLayoutFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout file/content map.
        /// </summary>
        public static string LayoutFileMapTitle {
            get {
                return ResourceManager.GetString("LayoutFileMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the layout file.
        /// </summary>
        public static string LayoutFileParsingErrorMsg {
            get {
                return ResourceManager.GetString("LayoutFileParsingErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MicrosoftGame.config in the provided folder is invalid.
        /// </summary>
        public static string MicrosoftGameConfigInvalidErrMsg {
            get {
                return ResourceManager.GetString("MicrosoftGameConfigInvalidErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MicrosoftGame.config lacks a valid Identity node.
        /// </summary>
        public static string MsftGameCOnfigLacksValidIdentityErrMsg {
            get {
                return ResourceManager.GetString("MsftGameCOnfigLacksValidIdentityErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logo file specified by the MicrosoftGame.config does not exist.
        /// </summary>
        public static string MsftGameConfigLogoFileNotExistErrMsg {
            get {
                return ResourceManager.GetString("MsftGameConfigLogoFileNotExistErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MicrosoftGame.config does not have the required Logo files in the ShellVisuals.
        /// </summary>
        public static string MsftGameConfigMissingLogoFilesErrMsg {
            get {
                return ResourceManager.GetString("MsftGameConfigMissingLogoFilesErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no files found in the layout file.
        /// </summary>
        public static string NoFilesInLayoutFileErrorMsg {
            get {
                return ResourceManager.GetString("NoFilesInLayoutFileErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string OptionalText {
            get {
                return ResourceManager.GetString("OptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the package output location.
        /// </summary>
        public static string PackageOutputBoxText {
            get {
                return ResourceManager.GetString("PackageOutputBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package output location.
        /// </summary>
        public static string PackageOutputTitleText {
            get {
                return ResourceManager.GetString("PackageOutputTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package path.
        /// </summary>
        public static string PackagePathTitleText {
            get {
                return ResourceManager.GetString("PackagePathTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string PackagePreviewFamilyText {
            get {
                return ResourceManager.GetString("PackagePreviewFamilyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package ID.
        /// </summary>
        public static string PackagePreviewPackageIdText {
            get {
                return ResourceManager.GetString("PackagePreviewPackageIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size estimate.
        /// </summary>
        public static string PackagePreviewSizeEstimate {
            get {
                return ResourceManager.GetString("PackagePreviewSizeEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreId: .
        /// </summary>
        public static string PackagePreviewStoreIdText {
            get {
                return ResourceManager.GetString("PackagePreviewStoreIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Preview.
        /// </summary>
        public static string PackagePreviewTitleText {
            get {
                return ResourceManager.GetString("PackagePreviewTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the game data path.
        /// </summary>
        public static string ProvideGameDataPathErrorMsg {
            get {
                return ResourceManager.GetString("ProvideGameDataPathErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredText {
            get {
                return ResourceManager.GetString("RequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mapping Data XML File.
        /// </summary>
        public static string SelectMapXmlTitleText {
            get {
                return ResourceManager.GetString("SelectMapXmlTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate your game&apos;s build to create a package. The Xbox Package Tool will remember these paths for easier access in the future..
        /// </summary>
        public static string SubTitleText {
            get {
                return ResourceManager.GetString("SubTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmissionValidator.dll not found in the specified path..
        /// </summary>
        public static string SubValDllNotFoundErrorMsg {
            get {
                return ResourceManager.GetString("SubValDllNotFoundErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a game package.
        /// </summary>
        public static string TitleString {
            get {
                return ResourceManager.GetString("TitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownText {
            get {
                return ResourceManager.GetString("UnknownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter the folder path for SubmissionValidator.dll.
        /// </summary>
        public static string ValidatorPathBoxDefaultText {
            get {
                return ResourceManager.GetString("ValidatorPathBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path for SubmissionValidator.dll.
        /// </summary>
        public static string ValidatorPathTitleText {
            get {
                return ResourceManager.GetString("ValidatorPathTitleText", resourceCulture);
            }
        }
    }
}
